server:
  port: 8082

spring:
  application:
    name: accounts-examiner

services:
  examiner:
    fixed-delay: 10
    initial-delay: 5
    threshold: 1

  external:
    url: https://api.coinlore.net/api/ticker

  internal:
    url: http://host.docker.internal:8081/api/v1
#    url: http://localhost:8081/api/v1

  mail-sender:
    url: http://host.docker.internal:8083/api/v1
#    url: http://localhost:8083/api/v1



